In [2]:
import numpy as np

temp = x = np.arange(1,10) #createas a numpy array of 1 -> 8
print(x)
print(x**4) #each element in x to the power of 4
x = temp #copies array from temp to x
print(x)

[1 2 3 4 5 6 7 8 9]
[   1   16   81  256  625 1296 2401 4096 6561]
[1 2 3 4 5 6 7 8 9]


<h3>1D Array

In [ ]:
#There another way to create an array
x = np.array([1,2,3])
x.ndim #gives the dimension of the array
print(x)

<h3>2D Array

In [ ]:
y = [3,4,21]
d2 = np.array([y,[7,8,90]])
d2 = np.array([[1,2,3],[4,5,6]])
d2.ndim #2d array
'''
The number of data in 1st array of this 2d array should be the same as the number of
elements in the second array.
'''

<h3>3d Array</h3>

In [ ]:
d3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(d3)

<h3>ND Array

In [ ]:
#Now lets create a 10 dimension array

d10 = np.array([1,2,3],ndmin = 10)
print(d10) 
d10.ndim

<h1>Functions on Arrays

<h3> Create arrays based on values they contain

In [ ]:
#Create an array of zero
zero_arr = np.zeros(4) #Creates a 1d array of 4 elements with all zero
print(zero_arr)
zero_arr2 = np.zeros((3,4)) #creates a 2d array of size 3,4
print(zero_arr2)

In [ ]:
#Create an array of 1

one1 = np.ones(5)
print(one1)

one2 = np.ones((3,4))
print(one2) 

In [ ]:
#Create an array of null

empty = np.empty(4) #creates an empty array of size 4
print(empty)

In [ ]:
#Array that conatins value in range
arr = np.arange(4) #0,1,2,3

print(arr)

arr = np.arange(2,10) #From 2 to 9

# alpha = np.arange('C','K') -> throws error

In [ ]:
#A matrix with diagonal elemets 1

arr_dig = np.eye(3) #Creates a 3x3 matrix with diagonal elemets 1

#using dimension
arr_dig = np.eye(3,5) #Creates a 3 x 5 array with diagonals 1
print(arr_dig)

In [ ]:
#Get elements with a particular gapping between two numbers

arr_lin = np.linspace(2,10,num = 10) # 10 numbers between 2 and 10 with same diffrence
print(arr_lin)

<h3> Random numbers

<h5>rand() -> generate random number between 0 and 1

In [ ]:

arr_rnd = np.random.rand(4) #creates an array of 4 elemets having random numbers between 0 and 1
# print(arr_rnd)

arr_rnd = np.random.rand(2,4) #creates a 2d array of 8 elemets having random numbers between 0 and 1
# print(arr_rnd)


<h5>randn() -> Generate random number close to zero, can be +ve and -ve.

In [ ]:
randn = np.random.randn(5) #5 numbers in the array

randn = np.random.randn(2,3) #2x3 numbers in the array, takes n(1,2...n) inputs
print(randn)



<h5>ranf() -> Generates random number between [0,1)

In [ ]:
ranf = np.random.ranf(5)

ranf = np.random.ranf((3,4)) #Creates 2x3 ranf() array, takes a tupple
print(ranf)

<h5>randint (min,max,total value) -> creates an array of integers betwen min and max value

In [ ]:
randInt = np.random.randint(5,6,3) #3 values between 5 and 10
print("hello")

<h1> Airthmetic Operation

<h2> 1D array

In [ ]:
var1 = np.array([1,2,3,4])
print(var1 + 3) #adds 3 to each element of the array

var2 = np.array([19,28,57,26])
print(var1 + var2) #adds var1 and var2 at respective index

var3 = var1 * 3
print(var3) #multipleis 3 in each element of var1 (same for + - / **{power} %{modulo})

var4 = var1 * var2
print(var4) #mulitplies var1 and var2 at respective index (same for + - / **{power} %{modulo})

var5 = 1/var1 #resiprocal , 1/[each element of var1]
print(var5)

<h4> Using Functions

In [ ]:
var = np.add(var1,3) #same as var1 + 3
print(var)
'''
We also have these functions
1- np.multiply(var1,var2)
2- np.subtract(var1,var2)
3- np.divide(var1,var2)
4- np.mod(var1,var2)
5- np.power(var1,var2)
6- np.reciprocal(var1,var2)
'''

<h2>2D array

In [ ]:
var = np.array([[1,2,3],[4,5,6]])
var2 = np.array([[7,8,9],[10,11,12]])

var3 = var + var2 

'''
1 + 7   2 + 8     3 + 9
4 + 10  5 + 11    6 + 12
'''
var3 = np.reciprocal(var3) 
'''
Will print all zeroes if you want floating number just add .0 to any of the number
i.e make them floating points
'''

var = np.array([[1.0,2,3],[4,5,6]])
var2 = np.array([[7,8,9],[10,11,12]])

var3 = var + var2 
var3 = np.reciprocal(var3) 

<h1> Arithmetic Functions

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9,0,-1])

<h3> 1D Array

In [21]:
np.min(arr) #finds the minimum value in the array

np.max(arr) #finds the maximum value in the array

np.argmin(arr) # gives the index of minimum value in the array

np.argmax(arr) # gives the index of maximum value in the

np.sqrt(arr) #finds square root of each value

np.cos(arr) #Cos value of each element

np.sin(arr) #Sin value of each element

'''
np.cumsum()

it will cumilatively adds the elements

our array -> 1 2 3 4 5 6

np.cumsum(array) 

will give output as
1 3 6 10 15 21

1 1+2 1+2+3 1+2+3+4 1+2+3+4+5 1+2+3+4+5+6
i.e sum of curernt element + sum of all elements before
'''
np.cumsum(arr)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_29692\1909501678.py:9: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr) #finds square root of each value


array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 45, 44])

<h3> 2D Array

In [15]:
var = np.array([[1,2,3],[4,5,6]])

In [25]:
'''
It is little complex to find min and max in 2D array

eg- np.min()
This takes two parameters 
    O Array
    O Axis
If we talk about axis it has two values 0 and 1. 
0 -> Take column wise
1 -> Take row wise
'''

np.min(var,axis =1)

'''
Output is [1, 4]
We took axis as 1 i.e row wise
1 2 3
4 5 6

Lowest element in row 1 -> 1 
Lowest element in row 2 -> 4

Hence the output is 1,4
'''

np.min(var,axis = 0)

'''
Output is [1, 2 ,3]
We took axis as 0 i.e column wise
1 2 3
4 5 6

Lowest element in column 1 -> 1 
Lowest element in column 2 -> 2
Lowest element in column 2 -> 3

Hence the output is 1,2,3

If you dont put the axis it will just return the max or min value in the entire array
'''

np.cumsum(var,axis = 1) #axis logic is same, only if you dont put axis it will display as normal 1d array



1